version: "3"

services:
  mysql:
    container_name: mysql
    image: mysql:latest
    volumes:
      - mysql-data:/var/lib/mysql
    env_file:
      - ./settings/.env.mysql.db
    ports:
      - 3306:3306
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - mongodb-data:/data/db
    env_file:
      - ./settings/.env.mongo.db
    ports:
      - 27017:27017

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    env_file:
      - ./settings/.env.express
    volumes:
      - mongodb-data:/data/db
    ports:
      - 8081:8081
    depends_on:
      - mongo

  backend:
    container_name: fastapi
    build: ./backend
    restart: on-failure
    env_file:
      - ./settings/.env.prod
    ports:
      - 8080:8000
    command: >
      ash -c "python3 wait_for_mysql.py  && uvicorn main:app --host 0.0.0.0 --reload"
    volumes:
      - ./backend/:/backend/
    expose:
      - 8080
    depends_on:
      - mongo
      - mysql

  spider:
    container_name: spider  
    build: ./backend
    command: ash -c "cd scraper && scrapy crawl base"
    volumes:
        - mongodb-data:/data/db
    depends_on:
        - mongo

  redis:
    image: redis:alpine
    command: redis-server --port 6379
    container_name: redis_boot
    hostname: redis_boot
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - 6379:6379


volumes:
  mongodb-data: null
  mysql-data: null
